# Generated by Django 4.2.21 on 2025-05-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicamentos', '0003_medicamento_laboratorio'),
        ('Farmacias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='medicamentos',
            field=models.ManyToManyField(to='Medicamentos.medicamento'),
        ),
    ]
