# Generated by Django 4.2.21 on 2025-05-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacias', '0002_farmacia_medicamentos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmacia',
        ),
    ]
