# Generated by Django 4.2.21 on 2025-05-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Laboratorios', '0001_initial'),
        ('Farmacias', '0003_delete_farmacia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('laboratorios', models.ManyToManyField(related_name='farmacias', to='Laboratorios.laboratorios')),
            ],
        ),
    ]
