# Generated by Django 4.2.21 on 2025-05-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('nombre_farmacologico', models.CharField(max_length=100, verbose_name='Nombre Farmacológico')),
                ('componentes', models.TextField(verbose_name='Componentes')),
                ('laboratorio', models.CharField(max_length=100, verbose_name='Laboratorio Fabricante')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre_comercial'],
            },
        ),
    ]
